# *********************************
# * Charba Travis-CI build script *
# * Copyright Â© 2019 pepstock.org *
# *********************************
#
# CONFIGURATION
#
# define the language
language: java
# enable container-based build (faster), instead of vm build
sudo: false
#
# SONARCLOUD
#
addons:
  sonarcloud:
    organization: "pepstock-org"
    token:
      secure: ${SONAR_TOKEN}
#
# CACHE
#
# cache the Ivy cache directory to avoid download dependencies on each build
cache:
   directories:
   - $HOME/.ivy2
   - $HOME/.ant
# specify the JDKs 
jdk:
   - oraclejdk8
#   - openjdk8
# specify the branches to build from
branches:
   only:
     - master
#     - stock
#
# BUILD phase
#
# download Ivy, if needed
before_install: ant buildInit
# run the ant main target
script: 
   - ant build-bin
   - sonar-scanner
# list the content of Ivy cache dir AFTER
after_script: ls -R ~/.ant 
#
# DEPLOY phase
#
#deploy:
   # do NOT clean the results
#   skip_cleanup: true
#
# NOTIFICATIONS
#
# notify the team on failures (successes are not notified)
#notifications:
#   email:
#      recipients:
#      - team@pepstock.org
#   on_success: never
#   on_failure: always
